meta:
  title: ESLint and TypeScript
  thumbnail:
  description: Introduction to TypeScript plugin for ESLint
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - typescript
      - javascript
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
  webpack:
build:
  ssr: true
